### ISSUE TITLE
kubernetes controller never starts apiserver

### ISSUE THREAD

**Issue by exarkun** [puppetlabs/puppetlabs-kubernetes#59]
Using puppetlabs-kubernetes 1.0.1 with an expression like:

    class { 'ntp':
        package_ensure     => 'latest',
        servers            => [ '0.ubuntu.pool.ntp.org', '1.ubuntu.pool.ntp.org' ],
        iburst_enable      => true,
        restrict           => [ '127.0.0.1' ],
    }

    class { 'kubernetes':
        controller           => true,
        bootstrap_controller => true,
        container_runtime    => 'docker',
    }

on an Ubuntu 16.04.3 system (on AWS EC2, image id ami-41e0b93b), the Kubernetes api server never comes up.  The kubelet logs complain that CNI has not been configured:

    Jan 31 16:33:19 ip-172-31-65-171 kubelet[9873]: W0131 16:33:19.982907    9873 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
    Jan 31 16:33:19 ip-172-31-65-171 kubelet[9873]: E0131 16:33:19.983012    9873 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

Though I don't know if this is the cause of the problem or a symptom of something else.

The kubetool invocation looks like:

```
MASTER=ip-172-31-65-171.ec2.internal
MASTER_IP=172.31.65.171

docker run -v $(pwd):/mnt \
    -e OS=ubuntu \
    -e VERSION=1.7.12 \
    -e FQDN=${MASTER} \
    -e IP=${MASTER_IP} \
    -e BOOTSTRAP_CONTROLLER_IP=${MASTER_IP} \
    -e ETCD_INITIAL_CLUSTER="etcd-kube-master=http://${MASTER_IP}:2380" \
    -e ETCD_IP="%{::ipaddress_eth0}" \
    -e KUBE_API_ADVERTISE_ADDRESS="%{::ipaddress_eth0}" \
    -e INSTALL_DASHBOARD=true \
    puppet/kubetool
```

I haven't tried to supply a CNI configuration myself.  From the README, it's not clear that I need to do this.

**Comment by scotty-c** [comment]
@exarkun By default, the module will install weave for CNI plugin.
In the newer versions, there is a choice, although I don't think this is the issue.
What do the etcd logs say?

**Comment by Bengrunt** [comment]
Hi there,

I've got the same issue on CentOS7 using v1.0.2 and weave.

I think it comes from a deadlock in the configuration of the `bootstrap_controller` node.
On this particular node, there is a step in  `service.pp` on [line 78](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/f70ce655e8783eb320f24a6abf63cb560d1b0a5a/manifests/service.pp#L78). 

It waits for the Kube API server to boot up but it lacks the weave configuration in `/etc/cni/cni.d`. 

However, the step that is supposed (I guess) to deploy the CNI configuration happens several steps later in the `kube_addons.pp` manifest, on [line 24](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/f70ce655e8783eb320f24a6abf63cb560d1b0a5a/manifests/kube_addons.pp#L24).

So I managed to boot the kube-apiserver with a dummy weave configuration file, manually put in `/etc/cni/cni.d`:
```
{
  "name": "weave",
  "type": "weave-net"
}
```
I stole it from this [weave issue](https://github.com/weaveworks/weave/issues/3005) on github.

And to answer @scotty-c's question: etcd's logs can't say much since at that point the etcd cluster has not even been created by puppet.

Hope it helps!

**Comment by scotty-c** [comment]
@Bengrunt you don't need configuration at all. There is a working example here with Puppet https://github.com/puppetlabs/kream and another project that uses CNI https://kubernetes.io/docs/setup/independent/install-kubeadm/ you will see the same in the logs until the CNI provider is installed. As soon as the kubelet service is started you should see etcd come up first. The code on line 78 makes sure the the cluster is ready for the networking provider. The Kubernetes API should come before the CNI plugin is installed

**Comment by Bengrunt** [comment]
My bad @scotty-c , etcd is created but crashed. When i look at the container logs I see something a bit weird:
```
2018-02-09 09:17:40.597844 I | etcdmain: etcd Version: 3.1.11
2018-02-09 09:17:40.598608 I | etcdmain: Git SHA: 960f4604b
2018-02-09 09:17:40.598626 I | etcdmain: Go Version: go1.8.5
2018-02-09 09:17:40.598725 I | etcdmain: Go OS/Arch: linux/amd64
2018-02-09 09:17:40.598803 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2018-02-09 09:17:40.599099 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-02-09 09:17:40.600180 I | embed: listening for peers on http://{MASTER_IP}:2380
2018-02-09 09:17:40.600612 I | embed: listening for client requests on 127.0.0.1:2379
2018-02-09 09:17:40.601006 I | embed: listening for client requests on {MASTER_IP}:2379
2018-02-09 09:17:40.638538 C | etcdmain: couldn't find local name "etcd-{MASTER_NAME}" in the initial cluster configuration
```
I feel like if it's trying to resolve the `etcd-{MASTER_NAME}` and fails which is normal since it does not exist. However, I didn't prefix the names of my etcd hosts with `etcd-` ...

Maybe that the missing CNI configuration does not really prevent the kube-apiserver from starting but the missing etcd does?

**Comment by Bengrunt** [comment]
Okay @scotty-c , our messages crossed :)

So, do I need DNS resolution names starting with `etcd-` on my etcd nodes?

**Comment by scotty-c** [comment]
So from the logs, it looks like you variables are not passing to hiera 
`2018-02-09 09:17:40.601006 I | embed: listening for client requests on {MASTER_IP}:2379`
The master ip needs to be an ip. The etcd name needs to be unique as its used for the raft consensus

**Comment by Bengrunt** [comment]
Thanks for the answer.

That is not a DNS resolution issue. I found what was wrong in my `etcd_initial_cluster` value: you need to use host names in the format "etcd-{NODE_NAME}" because this is what is hard-coded as the node name when the etcd container is booted, as can be seen [here](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/f70ce655e8783eb320f24a6abf63cb560d1b0a5a/templates/etcd.yaml.erb#L14). If what is passed to `--name` in the etcd container differs from what is passed to `etcd_initial_cluster` it will not work.

Maybe that's because I'm (obviously) new to the whole kubernetes/etcd world that I didn't realize this, but I feel like documentation could be improved there by explicitly specifying that you must prepend "etcd-" to the etcd cluster node names when you set the value of `etcd_initial_cluster`.

Afterwards, etcd came up and the kube-apiserver did as well.

Thanks!

**Comment by scotty-c** [comment]
Closing
